[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksPlan.phases.setup]
nodeVersion = "20"

[build.nixpacksPhase.install]
cmds = ["npm install"]

[build.nixpacksPhase.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npm start"
