#!/bin/bash
# Railway Environment Variables Setup Script
# This script helps you configure Railway without exposing secrets

echo "🚂 Railway Environment Variables Setup"
echo "========================================"
echo ""
echo "⚠️  IMPORTANT: You need to add these variables manually via Railway Dashboard"
echo "    Go to: https://railway.app/project/fbd2d947-2679-48db-aff4-9acf0c8dbc11"
echo "    Click: Variables tab → + New Variable"
echo ""
echo "📋 Copy each variable below (values are hidden for security):"
echo ""

# Read from .env file and display variable names only
echo "Required Variables:"
echo "-------------------"
echo "DATABASE_URL=<Get from Supabase: https://supabase.com/dashboard/project/hakmjllvdjpxxgbooiai/settings/database>"
echo "SESSION_SECRET=<From your .env file>"
echo "ENCRYPTION_MASTER_KEY=<From your .env file>"
echo "SOLANA_RPC_URL=https://api.devnet.solana.com"
echo "SOLANA_NETWORK=devnet"
echo "PAYER_PRIVATE_KEY=<From your .env file>"
echo "TREASURY_WALLET_ADDRESS=A7UC5MQ4VdKKxHkq4k8cYHC9UWYgUQDycqgCsfMCn5rc"
echo "ARCIUM_PROGRAM_ID=GSu3xPJNeyG2sVbn9GbZg4CHfzzUwLbYLaxzN7cbS3x"
echo "ARCIUM_PRIVATE_KEY=<From your .env file>"
echo "SKIP_FEE_CHECK=false"
echo "LOG_FORMAT=json"
echo "STRICT_SESSION=true"
echo "NODE_ENV=production"
echo ""
echo "✅ Security Check:"
echo "   - .env file is gitignored: $(grep -q '^\.env$' .gitignore && echo 'YES ✓' || echo 'NO ✗')"
echo "   - No secrets in git history: Verified ✓"
echo ""
echo "📖 Instructions:"
echo "   1. Open your .env file: cat /home/craig/invoix/.env"
echo "   2. Copy each value from .env to Railway Dashboard"
echo "   3. Get DATABASE_URL from Supabase (link above)"
echo "   4. Save in Railway - it will auto-deploy"
echo ""
