[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace_program = "F8XqbBJaKzpF5CWqmXR6uqutZ9HcNuiQAo7o5XgSYXrE"

[programs.devnet]
marketplace_program = "F8XqbBJaKzpF5CWqmXR6uqutZ9HcNuiQAo7o5XgSYXrE"

[programs.mainnet]
marketplace_program = "F8XqbBJaKzpF5CWqmXR6uqutZ9HcNuiQAo7o5XgSYXrE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "C:\\Users\\craig\\test-wallet.json"

[scripts]
test = "npx vitest run tests/marketplace.test.ts"
