[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace_program = "F8XqbBJaKzpF5CWqmXR6uqutZ9HcNuiQAo7o5XgSYXrE"

[programs.devnet]
marketplace_program = "F8XqbBJaKzpF5CWqmXR6uqutZ9HcNuiQAo7o5XgSYXrE"

[programs.mainnet]
marketplace_program = "InvxMkt3pA3hYn8V7JbmBKZ1FjJQX9YwqG5K6Zx8uP9m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'No tests'"
