[package]
name = "marketplace-program"
version = "0.1.0"
description = "Non-custodial marketplace for Invoix cNFTs"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marketplace_program"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.0"
anchor-spl = { version = "0.32.0", default-features = false, features = ["token"] }
solana-program = "3.0.0"

[profile.release]
overflow-checks = true
