[features]
seeds = false
skip-lint = false

[programs.localnet]
arcium_mxe = "5qs2TBEvAUEJiUVj7XupdjVxz9UyAxSy6mEkRSGyDbqe"

[programs.devnet]
arcium_mxe = "5qs2TBEvAUEJiUVj7XupdjVxz9UyAxSy6mEkRSGyDbqe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run tests/mxe.test.ts"
