[project]
name = "arcium_mxe"
version = "0.1.0"

[network]
cluster = "devnet"

[programs.localnet]
arcium_mxe = "GSu3xPJNeyG2sVbn9GbZg4CHfzzUwLbYLaxzN7cbS3x"

[programs.devnet]
arcium_mxe = "GSu3xPJNeyG2sVbn9GbZg4CHfzzUwLbYLaxzN7cbS3x"

[programs.mainnet]
arcium_mxe = "GSu3xPJNeyG2sVbn9GbZg4CHfzzUwLbYLaxzN7cbS3x"
